### ISSUE TITLE
loading on startup

### ISSUE THREAD

**Issue by szentigrad3** [petecory/Subterra-v2#2]
https://i.imgur.com/pWayuLa.png

**Comment by petecory** [comment]
Can you recreate the problem and share the factorio_current.log and the factorio_previous.log.

**Comment by szentigrad3** [comment]
[factorio-current.log](https://github.com/petecory/Subterra-v2/files/11553242/factorio-current.log)
[factorio-previous.log](https://github.com/petecory/Subterra-v2/files/11553243/factorio-previous.log)

**Comment by petecory** [comment]
Can you try this new version and see if it fixes the issue. 
[subterra-v2_0.1.2.zip](https://github.com/petecory/Subterra-v2/files/11554156/subterra-v2_0.1.2.zip)

**Comment by petecory** [comment]
I am able to recreate the issue by install all the mods your mods. It looks to be fixed. Please test and let me know. If this works I will commit and add an update to Factorio Mods. 
[subterra-v2_0.1.2.zip](https://github.com/petecory/Subterra-v2/files/11556149/subterra-v2_0.1.2.zip)

**Comment by szentigrad3** [comment]
> I am able to recreate the issue by installing all the mods you had. It looks to be fixed. Please test and let me know. If this works I will commit and add an update to Factorio Mods. [subterra-v2_0.1.2.zip](https://github.com/petecory/Subterra-v2/files/11556149/subterra-v2_0.1.2.zip)

confirm works

**Comment by petecory** [comment]
Thanks for reporting it! Update has been committed and published on factorio mods.
